FROM ubuntu:latest

LABEL maintainer="Ryuden <master+passmark@ryuden.org>"

RUN apt-get update \
    && apt-get install curl -y \
    && curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | bash \
    && apt-get install speedtest -y

WORKDIR /

ENTRYPOINT echo YES | speedtest
